-- Barford Golf Society 2027 dashboard and administrator security add-on.
-- Run only in the separate 2027 project: xspzmthygrajzktydvvj.

create table if not exists public.admin_role_audit (
  id bigint generated by default as identity primary key,
  changed_by uuid not null references public.profiles(id) on delete restrict,
  member_id uuid not null references public.profiles(id) on delete restrict,
  granted boolean not null,
  created_at timestamptz not null default now()
);

alter table public.admin_role_audit enable row level security;

drop policy if exists "Admins read role history" on public.admin_role_audit;
create policy "Admins read role history" on public.admin_role_audit
  for select to authenticated using (public.is_admin());

drop policy if exists "Members read own profile image" on storage.objects;
drop policy if exists "Signed-in members read profile images" on storage.objects;
create policy "Signed-in members read profile images" on storage.objects
  for select to authenticated using (bucket_id = 'profile-images');

create or replace function public.protect_profile_admin_flag()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.is_admin is distinct from old.is_admin and not public.is_admin() then
    raise exception 'Administrator access can only be changed by an administrator.';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_admin_flag on public.profiles;
create trigger protect_profile_admin_flag
  before update on public.profiles
  for each row execute function public.protect_profile_admin_flag();

create or replace function public.set_member_admin_access(
  target_user_id uuid,
  grant_access boolean,
  confirmation_name text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_profile public.profiles%rowtype;
  admin_count integer;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required.';
  end if;

  select * into target_profile from public.profiles where id = target_user_id;
  if not found then raise exception 'Member account not found.'; end if;

  if lower(trim(confirmation_name)) <> lower(trim(target_profile.full_name)) then
    raise exception 'The confirmation name did not match.';
  end if;

  if not grant_access and target_user_id = auth.uid() then
    raise exception 'You cannot remove your own administrator access.';
  end if;

  select count(*) into admin_count from public.profiles where is_admin = true;
  if not grant_access and target_profile.is_admin and admin_count <= 1 then
    raise exception 'The final administrator cannot be removed.';
  end if;

  update public.profiles
  set is_admin = grant_access, updated_at = now()
  where id = target_user_id;

  insert into public.admin_role_audit (changed_by, member_id, granted)
  values (auth.uid(), target_user_id, grant_access);
end;
$$;

revoke all on function public.set_member_admin_access(uuid, boolean, text) from public;
grant execute on function public.set_member_admin_access(uuid, boolean, text) to authenticated;

-- After running this add-on, make the first administrator once in SQL Editor:
-- update public.profiles set is_admin = true
-- where email = 'YOUR_ACCOUNT_EMAIL';
