const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const isAdmin=async(req:Request)=>{const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),auth=req.headers.get("Authorization");if(!url||!anon||!service||!auth)return false;const u=await fetch(`${url}/auth/v1/user`,{headers:{apikey:anon,Authorization:auth}});if(!u.ok)return false;const user=await u.json(),p=await fetch(`${url}/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=is_admin`,{headers:{apikey:service,Authorization:`Bearer ${service}`}});return p.ok&&(await p.json())?.[0]?.is_admin===true};
const decodeEntities=(value:string)=>value.replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&");
const decodeAstro=(node:any):any=>Array.isArray(node)?(node[0]===0?decodeAstro(node[1]):node[0]===1?(node[1]||[]).map(decodeAstro):node.map(decodeAstro)):node&&typeof node==="object"?Object.fromEntries(Object.entries(node).map(([k,v])=>[k,decodeAstro(v)])):node;
const total=(holes:any[],teeIndex:number)=>holes.reduce((sum,h)=>sum+Number(h.teeYardages?.[teeIndex]||0),0);
const chooseTee=(tees:any[],holes:any[],gender:"MALE"|"FEMALE")=>{
 const choices=tees.map((tee,index)=>({...tee,index,total:total(holes,index)})).filter(t=>t.gender===gender&&t.total>0);
 if(!choices.length)throw new Error(`No ${gender==="MALE"?"men's":"women's"} tee data was found.`);
 const preferred=gender==="MALE"?[/^yellow$/i,/gold/i,/member/i,/regular/i,/club/i]:[/^red$/i,/forward/i,/lad/i,/women/i];
 for(const pattern of preferred){const match=choices.find(t=>pattern.test(String(t.name||"")));if(match)return match}
 const byDistance=[...choices].sort((a,b)=>b.total-a.total);
 return gender==="MALE"?byDistance[Math.floor((byDistance.length-1)/2)]:byDistance[byDistance.length-1];
};
const cardFor=(holes:any[],tee:any,gender:"MALE"|"FEMALE")=>holes.slice(0,18).map((h,index)=>({hole:index+1,yards:Number(h.teeYardages?.[tee.index]),par:Number(gender==="MALE"?h.menPar:h.ladiesPar),stroke_index:Number(gender==="MALE"?h.menHandicap:h.ladiesHandicap)}));
const validCard=(holes:any[])=>holes.length===18&&holes.every((h,i)=>h.hole===i+1&&Number.isFinite(h.yards)&&h.yards>=40&&h.yards<=800&&[3,4,5,6].includes(h.par)&&h.stroke_index>=1&&h.stroke_index<=18)&&new Set(holes.map(h=>h.stroke_index)).size===18;
const clean=(value:string)=>value.toLowerCase().replace(/&/g," and ").replace(/\b(limited|ltd|golf|club|course)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
const slug=(value:string)=>value.toLowerCase().replace(/[’']/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const findPage=async(query:string)=>{
 const simplified=clean(query),words=simplified.split(/\s+/).filter(Boolean),terms=[query,simplified,words.slice(0,4).join(" "),words.slice(0,2).join(" ")].map(x=>x.trim()).filter((x,i,a)=>x.length>3&&a.indexOf(x)===i);
 const cards:any[]=[];
 for(const term of terms){const response=await fetch("https://18birdies.com/usercentral/api/course/searchPlaces",{method:"POST",headers:{"Content-Type":"application/json","User-Agent":"Mozilla/5.0 (compatible; BarfordGolfScorecard/1.0)"},body:JSON.stringify({key:term})});if(!response.ok)continue;const data=await response.json().catch(()=>null);for(const card of data?.clubCards||[]){const id=card?.clubBrief?.id?.id;if(id&&!cards.some(x=>x.clubBrief?.id?.id===id))cards.push(card)}if(cards.length)break}
 if(!cards.length)throw new Error("18Birdies could not find that course. Try shortening the course name or use the manual import.");
 const wanted=new Set(words),score=(card:any)=>{const brief=card.clubBrief||{},addition=card.clubAddition||{},candidate=clean([brief.name,brief.address,addition.cityName,addition.regionName,addition.countryName].filter(Boolean).join(" ")),tokens=new Set(candidate.split(/\s+/));let points=0;for(const word of wanted)if(tokens.has(word))points+=3;if(candidate.includes(simplified)||simplified.includes(clean(brief.name||"")))points+=12;if(/\b(england|uk|united kingdom)\b/i.test(query)&&/england|uk|united kingdom/i.test(candidate))points+=2;return points};
 cards.sort((a,b)=>score(b)-score(a));const best=cards[0],brief=best.clubBrief||{},id=brief.id?.id;if(!id||score(best)<3)throw new Error("18Birdies did not return a confident course match. Try a shorter name or use the manual import.");
 return `https://18birdies.com/golf-courses/club/${encodeURIComponent(id)}/${slug(brief.name||"golf-course")}`;
};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return reply({error:"Method not allowed"},405);if(!(await isAdmin(req)))return reply({error:"Administrator access required."},403);
 try{const body=await req.json().catch(()=>({})),query=String(body.query||"").trim();if(query.length<3)return reply({error:"A course name is required."},400);const sourceUrl=String(body.source_url||"").trim()||await findPage(query);const page=await fetch(sourceUrl,{headers:{"User-Agent":"Mozilla/5.0 (compatible; BarfordGolfScorecard/1.0)"}});if(!page.ok)throw new Error(`18Birdies returned ${page.status} for that course.`);const html=await page.text();const match=html.match(/<astro-island[^>]*component-export="Scorecard"[^>]*props="([^"]+)"/);if(!match)throw new Error("The 18Birdies scorecard data was not present on that page.");const props=decodeAstro(JSON.parse(decodeEntities(match[1]))),club=props?.profile?.club,holes=club?.holes||[],tees=club?.tees||[];if(holes.length<18||!tees.length)throw new Error("That 18Birdies course does not contain a complete 18-hole card.");const menTee=chooseTee(tees,holes,"MALE"),womenTee=chooseTee(tees,holes,"FEMALE"),men=cardFor(holes,menTee,"MALE"),women=cardFor(holes,womenTee,"FEMALE");if(!validCard(men)||!validCard(women))throw new Error("The selected tees did not contain a complete, valid 18-hole scorecard.");return reply({source_url:sourceUrl,course_name:club.name||query,layout:club.courses?.[0]?.name||"",men:{tee_name:menTee.name,total_yards:menTee.total,holes:men},women:{tee_name:womenTee.name,total_yards:womenTee.total,holes:women},available_tees:tees.map((t:any,i:number)=>({name:t.name,gender:t.gender,total_yards:total(holes,i)})).filter((t:any)=>t.total_yards>0)});
 }catch(error){return reply({error:error instanceof Error?error.message:"Automatic 18Birdies lookup failed."},502)}});
